# -*- coding: utf-8 -*-
"""Roni Merdiansah_Proyek Pertama : Membuat Model NLP dengan TensorFlow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqIEQErI3NA67AEN-aY22-_yXR_vwjib
"""

import pandas as pd

df = pd.read_csv('drive/MyDrive/Dicoding/BPML/Submission 1/dataset_review_tokped.csv')
df.head(5)

del df['Unnamed: 0']
df

# Mencari tahu info data seperti jumlah abris, kolom, tipe data, nilai null 
df.info()

df = df.astype(object)
df.info()

df.isnull().sum()

df = df.dropna()
df.info()

df.Rating.value_counts()

kategori = pd.get_dummies(df.Rating)
df = pd.concat([df, kategori], axis=1)
df.drop(df.columns[[1]], axis=1, inplace=True)
df

ulasan = df['Review'].values
print(ulasan)

from sklearn.model_selection import train_test_split

ulasan_latih, ulasan_test, kategori_latih, kategori_test = train_test_split(ulasan, kategori, test_size=0.2, shuffle=True)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000, oov_token='x', filters='!"#$%&()*+,-./:;<=>@[\]^_`{|}~ ')
tokenizer.fit_on_texts(ulasan_latih)
tokenizer.fit_on_texts(ulasan_test)

sekuens_latih = tokenizer.texts_to_sequences(ulasan_latih)
sekuens_test = tokenizer.texts_to_sequences(ulasan_test)

padded_latih = pad_sequences(sekuens_latih)
padded_test = pad_sequences(sekuens_test)

import tensorflow as tf
model = tf.keras.Sequential([
        tf.keras.layers.Embedding(input_dim=5000, output_dim=64),
        tf.keras.layers.LSTM(128),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(5, activation='softmax')
])
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.9 and logs.get('val_accuracy')>0.9):
      self.model.stop_training = True
      print("\nThe accuracy of the training set and the validation set has reached > 90%!")
callbacks = myCallback()

num_epochs = 50
history = model.fit(padded_latih, kategori_latih, epochs=num_epochs, 
                    validation_data=(padded_test, kategori_test), verbose=2, callbacks=[callbacks], validation_steps=30)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

"""Sebagian code mengambil referensi dari modul dan internet, harap dimaklumi jika terdapat beberapa kesamaan code 🙏😄~
Dan apabaila submission saya masih belum memenuhi ⭐5 harap di reject dan beritahukan saya yang kurang ~
Saya juga sangat menantikan feedback dari kakak kakak untuk menyempurnakan coding saya ~  Terimakasihh ~

Link Dataset

-https://drive.google.com/file/d/1p4Y-T2TAYh22WbjgJYTTXjKWmhe_W16r/view?usp=sharing

-https://www.kaggle.com/datasets/kulitekno/tokopedia-product-review-category-food-and-drink
"""